### ISSUE TITLE
Additional Field in Level 1.1 Mast Properties

### ISSUE THREAD

**Issue by agrangaraj** [IEA-Task-43/digital_wra_data_standard#104]
We can include  following attributes in Level 1.1 of WRA data model 

1. Mast_geometry_id : We can include non standard type WRA mast. For example if measurement taken from Telephone / Transmission tower eventhough it is lattice type these type of mast may impact the measurement result so the user need to account more uncertainity while carrying out data analysis. Similarly other possible options we may think off to include may be Hybrid structure, concrete, Mast in Building upstairs etc.,

2. Number of Levels: I think this can be derived as a calculated paramter from data. Can we include this additionally as a static information ?

3. Boom length, Thickness, Material. Am not sure whether this is already covered in WRA data model, I didnt find this information, Sorry if I missed somehow.

4. Mast Material : What type of material we used whether  galvanized iron or some other type

**Comment by abohara** [comment]
Thanks @agrangaraj 

Please refer to this [sql file](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/tools/iea43_wra_data_model_postgresql.sql) in the tools directory on implementing the schema locally.

1. The standard `Mast_geometry_id` that are available in the default list are "lattice_triangle", "lattice_square_round_edges", "lattice_square_sharp_edges", "pole" . [Doc](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-mast-properties.md#mast_geometry_id).<br>
These options directly link to properties in the mast properties table. If you have a non-standard geometry you can certainly add additional options on your local deployment to support any non-standard masts geometry (see .sql file above). The current default list is based on standard masts for WRA. If any of the options you stated above you believe would be valid for WRA then we should discuss those details further.

2. `Number of levels` - like you mentioned since it is a `derived` value, we early on decided that we would not support values that can be easily derived (there are so many of them). However, again you could modify your [`measurement_location`](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location.md) table in a local deployment to add this is a field

3. [`Mounting Arrangement`](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-measurement-point-measurement-point-properties-mounting-arrangement-mounting-arrangement.md) table has the boom related fields

4. `Mast material` could be helpful and we don't have it in there I believe. @stephenholleran  or @kersting  ?

**Comment by kersting** [comment]
@agrangaraj and @abohara `Mast material` is not accounted per the IEC standard. On the other hand, the shape of the tower is captured by the standard. Therefore I don't think we should include the material but any other geometries that depart from the specifications in the IEC standard.

**Comment by stephenholleran** [comment]
Regarding
> Mast Material : What type of material we used whether galvanized iron or some other type

@agrangaraj could you shed some light on what would the benefit of knowing this be? How would it be used? Thanks.

**Comment by agrangaraj** [comment]
OK can we  mention as a point in the documentation of the datamodel? so that user can get an idea to include such information, if they wish.

**Comment by stephenholleran** [comment]
Hi @agrangaraj,

Unfortunately we are not able to update the description of the notes for each specific property as notes is a common definition. So I have added to the description of the `mast_properties` and `mast_section_geometry` and allowed a user to add additional properties such as material. This should hopefully be ok for you?

See pull request #122
