### ISSUE TITLE
[DCC] mounting_orientation: change type to string?

### ISSUE THREAD

**Issue by heikowestermann** [IEA-Task-43/digital_wra_data_standard#113]
It was suggested to change the type of `mounting_orientation` from `quantity` (a numeric) to a `string`.

A few thoughts from me: Having a numeric has the benefit of beeing easily digestable by code. On the other hand a string might allow for a more free description of the setup. 
My original idea was to have the yaw orientation of the anemometer during calibration, as this is an influence parameter for directional sensitive devices (ultrasonic sensors with protruding arms/pillars are a common example).
I would leave it as a `quantity`, even if this is more strict, as this makes the data more accessible in the long run. If the value needs a more free description, the `notes` field could be used to describe the specifics of the value.

**Comment by kersting** [comment]
@heikowestermann I also support to keep it as numerical. I can see the IEC standard moving in a direction in which the directional dependency of the sonic becomes part of the standard. In that case having a numerical that we can write code to extract that number becomes very important.

**Comment by SFO-SOH** [comment]
@stephenholleran @heikowestermann The reason I suggested a string is that simply stating a quantity like "30 degrees" does not seem to be enough to clarify the setup orientation - e.g. for a (direction sensitive) cup anemometer without a north marker,
For a sensor with a north marker like a 3D sonic, a quantity might be adequate, although I can't rule out, that a quantity without an elaboration / definition might lead to misunderstandings (e.g. Cartesian vs. wind convetion for directions).
A supplemental "Notes"-string might solve the problem - and perhaps a defnition in the description like "For sensors with north markers, the mounting yaw orientation is defined as [...]".

**Comment by stephenholleran** [comment]
@SFO-SOH I was under the impression that the orientation would be referenced as the angle of attack from the wind direction in the wind tunnel. But you are saying there are other reference points?

If these reference points/lines can be defined could we do something like what we we do in the WRA Data Model i.e. we have an `orientation_reference` that is an enum with options magnetic_north, true_north and grid_north. Would something like `mounting_orientation_reference` with predefined options work?

You mentioned "Cartesian vs. wind convetion for directions". How does Cartesian work? Do you mean 'Polar coordinates'?

Thanks for the feedback!

**Comment by SFO-SOH** [comment]
@stephenholleran: I think it would be fair to define the mounting yaw orientation as: "The angle from the anemometer north marker to the upwind direction as measured clockwise when seen from above". If this is a fixed definition, a quantity will be adequate for sensors with a north marker. In this case, I think the definition should go in the json-schema file.

My primary concern is for anemometers _without_ a north marker - like (most) cup anemometers. For these, the definition above will not clarify the orientation during calibration. In this case, we would currently on the certificate state the mounting orientation during calibration as e.g. "Cable downstream" (if the cable is protruding horizontally from the anemometer body).

For cup anemometers which are _not_ directional sensitive, i.e. their calibration equation does not depend on the wind direction relative to the anemometers yaw orientation, the mounting orientation during calibration is not relevant. In this case we might state something like "Not relevant" for the mounting orientation on the certificate. 

However, some cup anemometers _are_ directional sensitive, and the mounting orientation during calibration is therefore relevant for the interpretation of the calibration results. I must admit that I'm not sure whether this information is actually used by anyone - but since it affects the obtained calibration equation, I think it should be stated.

**Comment by stephenholleran** [comment]
@SFO-SOH 
I think your definition is very good and I would be in favour of updating what we have with that.
> "The angle from the anemometer north marker to the upwind direction as measured clockwise when seen from above"

If an instrument is not directional sensitive then I would suggest that `mounting_arrangement` just isn't present. We can also include that advice in the description.

For the "Cable downstream" example and even for the "Not relevant" situation; there is the `notes` as part of this section where anything non-standard can be written. Would that cover off these situations? As these examples are not standard an analyst will need to read something to be able to interpret the orientation. It may not need to be the `mounting_orientation` attribute and so could be put into the `notes`. As there is no quantity to put into the `mounting_orientation` this would just not be present. For the majority of situations where there would be a quantity, the analyst will be able to read the value automatically with code.

@abohara thoughts?

**Comment by SFO-SOH** [comment]
@stephenholleran : This sounds good to me!

**Comment by stephenholleran** [comment]
> Change mounting_orientation to yaw_orientation 

Sounds good to me.

Could we still be more specific if the test item is not directionally sensitive as opposed to just assuming that you only need to use this "if the test item is directionally sensitive"?

Slight mod:
`
The yaw orientation/direction of the test item during calibration if the test item is directional**ly** sensitive. The angle is defined as the angle from the test item north marker to the upwind direction as measured clockwise when seen from above. **If your test item is not directionally sensitive you can simply leave this out or set as null.** Additional comments or alternative definitions should be added to the notes attribute (e.g. 'cable downstream').
`

**Comment by stephenholleran** [comment]
@heikowestermann any luck with creating a pull request for the DCC?

**Comment by heikowestermann** [comment]
@stephenholleran the missing piece was the updated screenshots of the schema and I figured out the problem. I will create the pull request tomorrow before the meeting!
