### ISSUE TITLE
[IEC validation requirements] Section height vs height of braces

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#152]
Looking at several met tower drawings, it was evident that it is an industry standard to show the height of the section instead of the height of the braces. One can derive the height of the braces by counting the number of braces and with the height of the section. The height of the braces actually many times is not provided in drawings. Perhaps we should get rid off the height of braces all together because it is a calculated variable.

**Comment by abohara** [comment]
@kersting Adding it makes sense. Don't think we need to subtract the existing field though (possibly put out a deprecation notice if needed)

**Comment by stephenholleran** [comment]
As discussed in our [meeting](https://github.com/IEA-Task-43/digital_wra_data_standard/discussions/129#discussioncomment-2333255), the following can be implemented:

> Mast section height vs height of braces. We quickly spoke about this one:
> 1. Add in mast section height.
> 1. Leave the braces height alone.
> 1. We need to record the number of diagonal braces vertically or the number of repetitive sections?

**Comment by kersting** [comment]
@stephenholleran and @abohara I started working on this. The mast section piece is straightforward. This will be applicable both the a lattice and a tube tower. However, I'm having a hard time to name point 3.

If we report the number of repetitive lattice member heights, whoever wants to derive the height of the entire section will need to divide the number of repetitive lattice members by 2, otherwise the section height will be computed twice as high. I guess that will be up to the analyst writing the IEC code to see that. The other alternative is to report the number of repetitive member heights along one leg. Using this parameters and the height of the lattice members, the analyst could derive the section height without dividing it by 2. I'm thinking about how the users will be using these numbers and that is why I'm bringing this to discussion. I'm inclined to use the first option but I'm living this problem right now so I know the pitfalls. I'd be interested in hearing your thoughts.

![image](https://user-images.githubusercontent.com/19154103/160171233-334cd609-641f-415e-ab34-a03df610c059.png)

**Comment by stephenholleran** [comment]
@kersting @abohara 
What I have marked in the red box is what we are trying to count within a section of mast tower.

![image](https://user-images.githubusercontent.com/25622575/160824072-fca93066-2dec-447b-a4f9-810c229785c6.png)

The `number of repetitive lattice members` I imagined would count the members highlighted in the image below. The member going up to the left is a different member and so not counted. I can see the confusion with this.
![image](https://user-images.githubusercontent.com/25622575/160834541-f8077a15-73c9-4a06-b859-a8d62e3d2c03.png)

Your suggestion of `number of repetitive member heights along one leg` would look like this?
![image](https://user-images.githubusercontent.com/25622575/160835421-c1f65b5a-7891-4781-9374-61b233b5997c.png)
What would someone do if they counted on the right leg? They could get 7 instead of 6.

I'm not sure which is better and to be able to explain without an image in the schema.

Another option is `number of repetitive patterns on face` to describe what I highlighted in the first image in this comment?

**Comment by stephenholleran** [comment]
Go for it @kersting.

**Comment by stephenholleran** [comment]
@kersting I have expanded on the description of `lattice_number_of_diagonal_bracing_members` to include the new 'repetitive_pattern' attribute as I noticed you increased that from 2 to 8. See commit [5383122](https://github.com/IEA-Task-43/digital_wra_data_standard/commit/53831224c5ec24635dac93366c2604d7c15fa061).

"The number of lattice diagonal bracing members **that are contained in one of the repetitive patterns making up a mast section**."

**Comment by kersting** [comment]
@stephenholleran thanks for updating that. Should we close this issue? I opened a new one that may have a bit of overlap with this one but I do see them as independent. 

https://github.com/IEA-Task-43/digital_wra_data_standard/issues/170

**Comment by stephenholleran** [comment]
Yep, lets close this.
