### ISSUE TITLE
[IEC validation requirements] Lighting finial diameter

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#156]
The IEC standard requires the lighting finial diameter to be 30 diameters away from the anemometer. I'd like to propose to include that information in the interference_structures table.

**Comment by abohara** [comment]
@kersting Agree. Looks like we need to do an IEC variables check (seems like you are doing it) and one branch for all these changes.

**Comment by stephenholleran** [comment]
@kersting I am assuming the information you want to include is the diameter of the lightning finial? And not the actual distance between it and the sensors as that could be worked out?

**Comment by kersting** [comment]
@stephenholleran and @abohara thanks for the feedback. Yes, we need the diameter of the lighting finial and not the distance. The IEC may decide to change the distance in the future as it happened for the distance between boom and cups. The diameter would survive regardless of the version of the standard. 

@stephenholleran if you're fine with that, I can start tackling this one.

**Comment by kersting** [comment]
@stephenholleran should I go ahead and include this in the example too or should I make a pull request for the modification in the schema first and then modify the example?

**Comment by stephenholleran** [comment]
@kersting yes please update everything that this would impact. 

This would include:
1. the schema file itself,
2. the database create SQL statements file, if any changes required (for this there would be),
3. the CHANGELOG and
4. the JSON example

**Comment by stephenholleran** [comment]
@kersting just reviewing this now and had a thought. This is in an `interferance_structures` table which allows the user to select a lightning finial or aviation light or something else. Wouldn't the diameter of the aviation light be useful to have as well? To gauge how big the interference structure is?

Therefore, I would suggest adding `diameter_of_structure` or `diameter_of_interference_structure` instead of just for a lightning finial. The 'diameter' may not necessarily mean that the structure is round but the term diameter would be an equivalent diameter, if it was square it would be the width of the square.

For lightning finial, aviation light, guy wires they are all round so the term diameter fits for them. For 'other' structures this diameter equivalent can be used to estimate the size.

Thoughts?

**Comment by stephenholleran** [comment]
Hi @kersting,

I suppose the diameter of the aviation light doesn't have a direct impact. The wake from the aviation light on an anemometer would be filtered out by assessing how wide the effected sector would be by doing a ratio of speeds with the paired anemometer by direction. The diameter doesn't have a direct impact with that. By having an aviation diameter though could help inform how big of an impact this might be or could help in building a drawing or 3D model of all the components of the mast to help show a wind analyst where and how big the aviation light is and what to expect to see in the data i.e. the analyst would know they need to filter out wind speeds from a certain direction sector.

You are right, not a direct impact on the numbers but might be useful to have. It is also not great database design having a lightning finial diameter empty when it is an aviation light. I more generic diameter could then be used for an aviation light.

**Comment by stephenholleran** [comment]
@kersting I expanded on the description. See commit [2f5f60f](https://github.com/IEA-Task-43/digital_wra_data_standard/commit/2f5f60ffc06feb11cb0dc6235a2b1c22efe81c39),  just above, to make sure you are happy with it.

**Comment by stephenholleran** [comment]
@kersting are you happy with the above?
It is already merged into dev branch so no pull request to review. If you are happy just close this issue. Cheers.

**Comment by kersting** [comment]
@stephenholleran it is good for me. Thanks for reviewing!
