### ISSUE TITLE
Should lidar be listed in the sensor type enums?

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#186]
@abohara, @stephenholleran, and @heikowestermann During an implementation of a ZX lidar in our database, I came across the need to differentiate between a measurement point measured by the short mast attached in the lidar vs the one measured by the lidar. This is an important distinction when it comes to data cleaning. Currently the data model does not allow one to perform that because lidars are not in the list of sensor types. Should we include lidars in the list of the sensor table? I advocate for including because of the case above. I can create the pull request for that. Let me know your opinion.

**Comment by stephenholleran** [comment]
Hi @kersting,

If I understand correctly, the issue is to distinguish between the 2 wind speeds, one from the lidar and the other from the anemometer? I am assuming you have certain cleaning algorithm for cleaning lidar data that is not appropriate for an anemometer.

Is the height that they measure at a way to distinguish between the 2?
Would you have the data model set up that the anemometer has a 'sensor_type' anemometer and therefore can exclude that?

**Comment by abohara** [comment]
Hi @kersting 

Yes. I support having , `lidar`, (and by similar argument `sodar` ) as a `sensor_type` in addition to being a `measurement_location_type` as well ( we do it internally ). It does make the data tables appear a little more consistent.

**Comment by stephenholleran** [comment]
OK, we can add it so. The user doesn't have to have a sensor for a lidar if they don't want to.

Will it cause confusion with where the settings of the lidar (or sodar) are put i.e. they should go into 'logger_main_config' or 'sensor'?

**Comment by kersting** [comment]
@abohara and @stephenholleran ready to be reviewed: https://github.com/IEA-Task-43/digital_wra_data_standard/pull/188

**Comment by stephenholleran** [comment]
I took this on and GK reviewed.
