### ISSUE TITLE
[SCHEMA] Measurement location UUID

### ISSUE THREAD

**Issue by jonssonchristian** [IEA-Task-43/digital_wra_data_standard#232]
I am part of a working group creating a data model (digital exchange format) for wind EYA data. For measurement station metadata, we use the IEA Wind Task 43 WRA Data Model (for that sub-model, we reference the WRA Data Model JSON Schema from our JSON Schema).

Elsewhere in the EYA Digital Exchange Format (EYA DEF) schema, we need to be able to reference the different measurement stations. For example, long-term wind speed results at the measurement locations need to be "tagged" with a measurement station identifier.

In the IEA Wind Task 43 WRA Data Model, each item under `measurement_location` has a property `name`. Currently we use this name field as the unique identifier when referencing specific measurement stations elsewhere.

In your view, is the `name` field suitable for this purpose? Would it make sense to include guidance in the description of this field, to highlight that it should be selected such as to be unique within the context of a project. I would expect issues with colliding names to be very rare, but suppose it could happen, for example when combining documents from different organisations, who have used the same name for different measurement stations.

Alternatively, could it make sense to include an `id` field in addition to name, which could be less human readable but less likely to clash? That could for example be a UUID.

For the purpose of having a short measurement station label in graphics and tables, would it make sense to include an optional `abbreviation` field, as a shorthand for the name.

**Comment by abohara** [comment]
Hi @christianjnaturalpower . 

All tables (including `measurement_location`) rows generally have a `uuid` identifier, but a lot of the `uuid` field descriptor are left out of the schema definition (perhaps considering it just an implementation detail of the storage). In the [postgres example](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/8a68e0315ee9a7dbbb04eeaadd9bf739f9c24d50/tools/iea43_wra_data_model_postgresql.sql#L308), we do have it.

**Comment by stephenholleran** [comment]
Hi @christianjnaturalpower,

Good timing with your question as we have just had a group meeting where we brought this up.

We can see a potential issue with name conflicts when bringing together neighbouring projects. It would be very rare but could happen. Therefore, we are willing to include a `uuid` field at that level, it would be optional and follow the uuid format. Thinking about it a bit more we should probably call it `measurement_location_uuid` instead of just `uuid`.

We can also improve the description of the measurement_location name to encourage users to use unique names.

Regarding your other question about an abbreviation for the name. We didn't feel this was helpful at this time as it may cause confusion in what the measurement location is actually called. It is really up to the user to name it whatever they want and I suppose we would encourage users to use as short a name as possible. In your context, producers of EYA reports mostly do this already. If it becomes an issue in the future we would definitely revisit.

Do you want to have a go at these changes?

Cheers,

Stephen

**Comment by stephenholleran** [comment]
Hi @christianjnaturalpower ,

Sorry for the slow response.

You wrote:
> Sure, if you give me feedback on the question of whether we call it just `uuid` or `measurement_location_uuid`, I can draft a PR.

You are right, `uuid` will be fine. As you say it has a parent so we know which one it is.

**Comment by christianjnaturalpower** [comment]
Hi @stephenholleran, now it is my turn to apologise for a delayed response. I finally prepared updates for a PR but was unable to push my branch since I do not seem to have the required access rights (see below). Would you be able to give me permission to push to the repo?

![image](https://github.com/IEA-Task-43/digital_wra_data_standard/assets/98944372/1622090e-d100-414b-894e-d57a81c7c1f4)

**Comment by stephenholleran** [comment]
Hi @christianjnaturalpower,
You shouldn't be able to push to the master branch or even the dev branch. What you should do is branch off the most recent dev branch where you can work on this specific issue. Once you are happy you can then create a pull request to merge that feature branch into the dev branch. I'll be able to review it then and merge when we are happy. After a few changes to the dev branch we will then do a new release where we merge that dev branch into master. I'd hope to do one of those before the end of the year.

Check out the contributing file for more details or ask if you have any questions.
https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/contributing.md

**Comment by christianjnaturalpower** [comment]
Hi @stephenholleran, thanks, I had missed that. I was not trying to push to the `master` or `dev` branch, but had created my branch for the issue off the `master` branch rather than the `dev` branch, so I presume that will be why it failed. I will sort that.

**Comment by christianjnaturalpower** [comment]
Hello again @stephenholleran, I merged my issue branch with the latest `dev` branch but still get the same error message. Are you sure that I do not need some permissions to be able to push a new branch to the repo?

**Comment by stephenholleran** [comment]
Merged. Thanks @jonssonchristian.
