### ISSUE TITLE
Add optional field 'column_label' to 'column_name' under 'logger_measurement_config'

### ISSUE THREAD

**Issue by jonssonchristian** [IEA-Task-43/digital_wra_data_standard#249]
I have been doing some work integrating a workflow using the IEA Task 43 WRA Data Model with Windographer. The Windographer data model for a time series data column includes both a column ID and a column label. When importing from or exporting to the IEA Task 43 WRA Data Model, the column ID is mapped to `measurement_location.measurement_point.logger_measurement_config.column_name.column_name`. The interoperability could be enhanced if an optional field `measurement_location.measurement_point.logger_measurement_config.column_name.column_label` was added to the WRA Data Model to also allow capturing the Windographer column label data. For example, when exporting time series data files, Windographer uses the column labels and not the IDs, so there is a mismatch with the names in the IEA Task 43 WRA Data Model JSON export (i.e. it is not possible to match up column names with column headers in the exported time series).

Aside from Windographer interoperability, I also think it would be useful in general to support a label for a column that can be different from the column header names in a text file or ID in a database. Sometimes those names cannot be controlled and may not provide a good label to display in graphics or tables.

Below is a minimal example of what I imagine a JSON document with an added `column_label` field could look like.

```json
{
  "author": "jonssonchristian",
  "date": "2024-01-31",
  "measurement_location": [
    {
      "latitude_ddeg": 1.23,
      "longitude_ddeg": 4.56,
      "measurement_point": [
        {
          "height_m": 110.0,
          "logger_measurement_config": [
            {
              "column_name": [
                {
                  "column_name": "TFCA_110m_TOP;Avg",
                  "column_label": "Wind speed 110 m",
                  "statistic_type_id": "avg"
                }
              ],
              "date_from": "2022-02-24T00:00:00+01:00",
              "date_to": "2023-03-03T08:40:00+01:00",
              "measurement_units_id": "m/s",
              "offset": 0.198234,
              "slope": 0.053959
            }
          ],
          "measurement_type_id": "wind_speed",
          "name": "TFCA_110m_TOP;Avg"
        }
      ],
      "measurement_station_type_id": "mast",
      "name": "bar",
      "update_at": "2024-01-31 10:34:20Z"
    }
  ],
  "organisation": "KUDO",
  "plant_name": "foo_wind_farm",
  "plant_type": "onshore_wind",
  "version": "1.1.0-2022.06"
}
```

I suppose an alternative would be to include a optional label at the `measurement_point` level rather than column level. That would however leave less flexibility and would not solve the issue of interoperability with the Windographer data model.

**Comment by abohara** [comment]
@jonssonchristian Thanks for bringing the issue up. 

It sounds like for Windographer interop as well as for easier readability ( both helpful goals) you would like the option to have a 'column_label' in addition to the standard 'column_name'. From what I can see, this could be done in your local deployment / process without a need to modify the core Task 43 schema. The Task 43 schema goals are primarily to document the metadata related to the campaign and minimize tracking of derived information or additional tracking beyond. The `column_label` here would indicate an internal naming preference or tracking tool, but not necessarily illuminate much on measurements.

Apologies if I misunderstood your intent and obviously open to further discussion.

**Comment by jonssonchristian** [comment]
Hi @abohara,

Thank you for the feedback. You have understood my suggestion correctly.

I see your point about focusing on core measurement campaign metadata and avoiding the schema growing to include all sorts of derived data and annotations. As I understand it, the purpose of the `column_name` field under `logger_measurement_config.column_name` is to allow matching up the column and measurement point metadata with data columns in the measurement dataset. In other words, that field does not illuminate anything on the measurements themselves but is just to facilitate mapping against a measurement time series dataset. Of course without a unique ID (in this case the `column_name`), there would be no way of uniquely referencing the metadata for each column, which would make the metadata kind of useless. So that ID is obviously important to have in the model.

If I understand your suggestion directly, I should rather than including a column label in the IEA Task 43 WRA Data Model JSON file have a separate mapping where I store a column label for each column ID (`column_name`). For an internal application, that would certainly work and be a satisfactory solution. The limitation with tracking it separately, however, is that I then also need to transmit it separately when exchanging data with external systems. The use case I primarily had in mind was to be able to load the IEA Task 43 WRA Data Model JSON file into Windographer, and it would read both the ID and the label, and similarly on data export. The Windographer development team have indicated that they would support this. If I include that additional field to the JSON file without it being part of the schema, the schema validation would fail (since `additionalProperties` is set to `false`). So as far as I can see, the only way to achieve that enhanced workflow would be to add the field as optional to the schema.

It should be a bad idea to add items to the schema only to support specific integration with particular software tools. In my view this would however be a piece of information useful to include more widely in metadata exchange. Not critical of course, but useful. It could be exchanged separately, but it would be more cumbersome to exchange two different metadata files than just one. If it is an optional field (I would definitely not propose making it required), no one would have to include it, but people who want to use it for data exchange could do so without schema validation failing. I think that would be helpful to more users than me.

**Comment by stephenholleran** [comment]
Hi @jonssonchristian,

Thanks for this question.

From my understanding the new suggested `column_label` would give a more understandable idea of what that column of data represents. You suggested that this would help when column names in a logger data file are fixed, such as NRG where they ae CH1Avg which means nothing. 

The whole point of the data model is to give meaning to the data columns from these logger data files. The `measurement_point.name` is effectively what you are asking for. In your example above I would have used "Wind speed 110 m" for the measurement point name instead of "TFCA_110m_TOP;Avg".

The main reason why I suggest you should use the `measurement_point.name` is that the data column in the logger files can change what it is actually reading part way through a measurement campaign. Having a `column_label` at the column level to give it meaning would then be out of date. I'll try and explain with some diagrams.

The [demo data model](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/demo_data/iea43_wra_data_model.json) file in the repo contains part of an example to demonstrate this. Flattening the data model into the below table you can see that the 'Spd_40mNW' measurement point anemometer was connected to CH5 and then part way through it was rewired to CH14. And 'Spd_30mNW' anemometer was inadvertently mounted at the wrong height and so was moved from 30 m to 40 m and the logger channel was changed from CH6 to CH13.

![image](https://github.com/IEA-Task-43/digital_wra_data_standard/assets/25622575/9ab2d801-700c-4cba-9366-229a2994c34f)

Assembling the raw logger timeseries files with their column names would look like the following. Working with this data isn't what a wind analyst needs as the 'Spd_40mNW' data is actually spread over two data columns, CH5Avg and CH14Avg.

![image](https://github.com/IEA-Task-43/digital_wra_data_standard/assets/25622575/0f845d50-e19b-47f3-864a-1607e207b7a9)

The assembled timeseries data that a wind analyst needs is to the right in the below diagram. The original columns need to be chunked and reassembled into a single column that represents an actual continuous measurement, e.g. 'Spd_40mNW', which is what the wind analyst needs. The new column name for this data is the measurement point name as that is what the new assembled column represents.

![image](https://github.com/IEA-Task-43/digital_wra_data_standard/assets/25622575/3b3429a0-dc4d-4f5c-8fb2-bfb65e56ebde)

Having a `column_label` at the column name level would then need to be updated at the time of the change to keep the meaning up to date. We all know that this wouldn't happen and so therefore it's usefulness is diminished and would just cause more confusion. It is also something that isn't available in the logger files to keep track of. I don't know how Windographer assembles data like this and where their `column_label` goes. I would recommend that this `column_label` should be mapped to the `measurement_point.name` if it is used to label the assembled column of data.

What could also happen quite easily in the above example is that another sensor, maybe not even an anemometer, could have been wired to channel CH5 or CH6 at the time of the changes. The data model can handle this and using the measurement point name for the assembled timeseries would give meaning to the appropriate columns.

**Comment by jonssonchristian** [comment]
Hi @stephenholleran, thank you very much for your detailed response.

Your argument makes full sense to me and I agree. I got somewhat blinded by looking at a narrow use case of working with data already assembled in Windographer, whereas the data model is of course primarily aimed to capture the metadata for the raw data.

When I import raw data files into Windographer, I do the mapping from raw column names to 'assembled' column names. So if the channels are swapped during the measurement campaign I will change the mapping accordingly so that the assembled columns each correspond to single measurement point. When I then export a time series data file and metadata file, it is the assembled (and filtered) data that are exported, not the raw data.

With the purpose of the T43 data model being to describe the measurement configuration and raw measurement dataset (as I understand it), it should not make sense to change anything to cover column mappings for processed data. That would probably very quickly grow into a mess.

I agree that, when working with assembled and processed data, the relevant reference should be the name of a measurement point rather than the name of a column, as the columns refer to raw columns and the measurement point to the actual sensor or other point of measurement, for which data has been assembled.

Based on this, it seems the most useful export from Windographer of the `logger_measurement_config` data would be to use the data import history and map out how the raw columns were combined into the assembled columns. Then if `measurement_point.name` is included in all exports of time series column data, it would be possible to map it to the metadata. There would just need to be an identifier on each assembled column to describe the statistic type (mean, standard deviation, etc.), but that generally follows standard tags.

Currently Windographer uses the 'parent' (mean) column ID as `measurement_point.name`. If they change that to use the parent column *label* instead of the ID, I think the interoperability issue would be solved. The label in their data model I think better corresponds to the name of the measurement point in the T43 data model, as the ID typically comes from a raw data column identifier and is often not meaningful.

I suppose one could argue that it may be useful to have separate measurement point IDs and labels. But if the names are chosen to serve as useful labels, they can serve as both labels and IDs. You would never use the same name for different measurement points on the same measurement station, and there is no need for them to be unique outside of the measurement station (perhaps so in a database, but that is an implementation detail that does not need to be included in data exchange).

Does that sound reasonable to you? If you agree, I will suggest to the Windographer development team that they change the mapping of parent column ID to `measurement_point.name`, and instead map parent column label to `measurement_point.name`. Mapping out the raw data import would also be great, but I imagine that would be more work to implement.

**Comment by stephenholleran** [comment]
Hi @jonssonchristian,

Yeah, that makes sense to me, map parent column label to measurement_point.name.

To cover the different statistic types we do tag on the statistic type ([as listed in the T43 data model](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/e590563e9f6d6987c5f267055f0b542be0970f2e/schema/iea43_wra_data_model.schema.json#L1178)) to the end of the measurement point name in the resulting timeseries data file e.g. `Spd_40mNW_sd`, `Spd_40mNW_max`, '`Spd_40mNW_min`.

Cheers,

**Comment by jonssonchristian** [comment]
That sounds like a good idea. The default tags for standard deviation, minimum and maximum in Windographer are different, but it is just a question of simple mapping.

I will make the suggestion to the Windographer development team and let you know what response I get. From my perspective this issue could now be closed, but I let you decide whether to close it or leave it open.
