### ISSUE TITLE
Tag or release version 0.1

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#29]
Tag or release or launch version 0.1.0-202011. The below might be the thing to do?
https://git-scm.com/book/en/v2/Git-Basics-Tagging

@Dynorat @sdsmdp maybe you have a different way of tagging or releasing a version?

Do this once issue #19 has been merged.

**Comment by stephenholleran** [comment]
Hi @jordanperr,

I was looking at the OpenOA GitHub repo and see that you have tags/releases for that software. I know OpenOA is a piece of code that gets installed via pip but maybe you have some advice that might be applicable for us to version, tag or release our data model?

We have already decided on the labeling of the versions outlined in the [contributing ](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/CHANGELOG.md) file. I'm just looking for advice on implementing it correctly and according to best practice?

Thanks,

Stephen

**Comment by stephenholleran** [comment]
Note:
We might need to put somethinng within the schema file itself to state the version.

Below is what is in there now. The keys beginning with a '$' are to highlight information about the schema and is not part of the schema itself.
```{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/IEA-Task-43/digital_wra_data_standard/master/schema/iea43_wra_data_model.schema.json",
```

We may need to add something like `$version` into this.

**Comment by sdsmdp** [comment]
I agree, @stephenholleran, that there needs to be some method to identify the schema version.

This carries over from the JSON to any database implementation of the schema, as well. I would recommend a separate entity (table) within the database that holds schema metadata. At the moment, that may consist of just the version number. We can use this facility in conjunction with SQL DML scripts to apply schema updates over time as the schema evolves. For example, scripts could contain conditional logic based on the schema version and each script or set of scripts would contain an update statement to set the resulting schema version.

Perhaps that database implementation suggestion also suggests an approach on how to reflect the schema version of the JSON. I lean toward it being content within the file rather than part of the filename, but your mileage may vary.

**Comment by stephenholleran** [comment]
>  I lean toward it being content within the file rather than part of the filename

I'll implement it within the schema itself.

Regarding the database side of it. If I understand you correctly that could get complicated. I suppose the main thing is the Data Model itself. The database schema is a 'nice to have' seen as we pretty much designed it based on a database schema but it isn't essential. What I'll do is create another issue with your comment so it doesn't get lost. It is more for updates anyway so not critical for this first v0.1.
