### ISSUE TITLE
Bug: Broken Link

### ISSUE THREAD

**Issue by kilojoules** [IEA-Task-43/digital_wra_data_standard#46]
The page https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-measurement-point-measurement-point-properties-sensor-sensor-properties-calibration-calibration-properties-calibration-uncertainty-calibration-uncertainty.md has broken links. When I click `IEA Wind Resource Assessment - Data Model`, it links to a 404 page.

**Comment by abohara** [comment]
@stephenholleran @flrs-edf Any idea how these are generated ? Or what might have caused broken links ?

**Comment by abohara** [comment]
@stephenholleran @flrs-edf  I just tried to clone the repo and it threw up errors that some of the filenames in the docs were too long. Any suggestions on how to shorten it ? I wonder if this is the causing the broken links.

![image](https://user-images.githubusercontent.com/6306857/106234705-26e9ea80-61ae-11eb-8059-fd9aee756005.png)

**Comment by stephenholleran** [comment]
Hi @kilojoules,

Thanks for letting us know.
I just clicked the link in your first post and it seems to work fine for me. I even cleared out my cache in case it was loading from there. Is it still broken for you? 

@abohara 
These pages are automatically created so I'm not sure if we have any control over that. They are very long and yes, if you are trying to open them in Windows you will most likely have a problem. I have had major problems in the past with the Windows file name/path character limit. The only solution I can think of is to find a different tool to auto-create the documentation from the JSON Schema.

**Comment by stephenholleran** [comment]
@abohara 
This I think is one of the longest file names in my local repo:
```
C:\BW\RTD\repos-Stephen\digital_wra_data_standard\docs\iea43_wra_data_model-properties-measurement-location-measurement-location-properties-measurement-point-measurement-point-properties-sensor-sensor-properties-calibration-calibration-properties-calibration-uncertainty-calibration-uncertainty-properties.md
```
It is 309 characters long.

This[ Stack Overflow](https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows) post might help. I may have done something to allow me to clone previous repos and so haven't had a problem with this one.

**Comment by flrs-edf** [comment]
@stephenholleran, I also found the broken link in the file @kilojoules described, it is this one:

https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/docs/iea43_wra_data_model-properties-measurement-location-measurement-location-properties-measurement-point-measurement-point-properties-sensor-sensor-properties-calibration-calibration-properties-calibration-uncertainty-calibration-uncertainty-properties-reference-bin.md

The docs are created automatically (and so are the extremely long file names). I think the brand new (and merged) pull request https://github.com/adobe/jsonschema2md/pull/274 takes at least the `properties` out of the file names, so that they may shrink a little bit.

The way the [compile docs GitHub action](https://github.com/IEA-Task-43/digital_wra_data_standard/blob/master/.github/workflows/compile_docs.yml) is set up, it should pick up on the change above, since we are pulling jsonschema2md directly from npm.

**Comment by stephenholleran** [comment]
Cheers @flrs-edf, that is a new release alright. 12 days ago whereas our last commit to master was 19 days ago.

I don't know how this workflow works. Is there a way to kick off running the documentation creation on GitHub without having to commit something to master?

**Comment by stephenholleran** [comment]
The documentation workflow was manually ran by going to actions - Compile Documentation to Markdown - Run Workflow

Links seem to work now.

![image](https://user-images.githubusercontent.com/25622575/106932054-2a7df400-670f-11eb-9fbb-518afb32aaa4.png)
