### ISSUE TITLE
[schema] make measurement_location an object instead of array

### ISSUE THREAD

**Issue by stephenholleran** [IEA-Task-43/digital_wra_data_standard#50]
At present the Data Model has measurement_location as an array. This means that many met masts can be contained in a data model for the one wind farm. 

This can make the data model very large and difficult to navigate, even with code. In code, if a class is created for a met mast it is not possible to have many instances of this class if many met masts are included in the data model without having a wind farm class. For an analyst, it is easier to deal with each met mast on its own and they can amalgamate them when needed in the analysis. Having many met masts in the one data model makes it more difficult to manage from a file management perspective too.

I am recommending that each data model implementation should only contain one met mast (or measurement_location)?

**Comment by sdsmdp** [comment]
I support your recommendation, @stephenholleran. To the best of my knowledge, analysts currently only deal with data files from a single mast (or the equivalent; e.g., a single lidar). Moreover, in every use case for combining data I've heard discussed, the desire has been to combine time series data that may have initially been gathered for a shorter time range (e.g., 1d) into a file that spans a longer time range (e.g., 1 mo., 1 yr., etc.). I do not believe I have heard a request to view data from more than one device within the same file in order to communicate data from across a whole farm/project. Therefore, I agree we should remove the array and limit the mast (or equivalent) to a single instance. We can revisit in the future if we start to hear feedback/requests for multiple instances.

I am assuming you are speaking of the JSON schema only. Would you agree that a database implementation would support multiple masts (or equivalent)? (That's where we made provision for the associated parent entity (wind farm), as well.)

**Comment by stephenholleran** [comment]
Hi @sdsmdp ,
Thanks.
Yes, this is just for the schema. For the database there will be many masts, lidars, sodars sometimes all on the same site.

**Comment by kersting** [comment]
For me it makes sense to have as an object as well. The analyst can create a collection of those objects and iterate over them if multiple met masts need to be analysed together (which is usually the case). For me this is cleaner than having a long array of measurement locations.

**Comment by sdsmdp** [comment]
Yes, @kersting, I agree with using a collection if/where needed rather than an array. That is generally much more powerful, anyway.

**Comment by abohara** [comment]
@stephenholleran I am a little unclear about your request. Are you advocating that data for only one location be allowed per file ( e.g. per JSON) ? So, if a project has 5 towers you prefer for it to be spread across 5 JSON files ?

If you would like to do that now, I don't think the JSON schema stops you from doing it ? For e.g. ```measurement_location[0]['name'] ``` ? You can implement that as a guideline within the org no?
Enforcing one file per schema however would take away the option for orgs who would prefer to have all metadata in a single file (assuming we are still just talking about metadata). As an interchange format a single file is certainly preferable over multiple files (for one, you can avoid the integrity checks that all files do belong to the same file or are not duplicates).

If we are trying to create a better UX for the user (whether in code or UI), each org could develop their own abstraction over the base schema that is suitable for the org's work process. Constraining the schema to a particular access pattern or programming style I don't think is beneficial.

**Comment by stephenholleran** [comment]
Lets discuss on tomorrows call. Thanks.

**Comment by stephenholleran** [comment]
A solution could be for the code to convert the list into a dictionary with the name of the measurement_location as the key. 

Consider SQlLite as an option.
