### ISSUE TITLE
[DCC] calibration_organisation in its own table

### ISSUE THREAD

**Issue by kersting** [IEA-Task-43/digital_wra_data_standard#54]
Given that calibration organizations don't change very often and that not many are out there. Should we create a table similar to the logger_oem table?

**Comment by heikowestermann** [comment]
From a maintainability standpoint I somehow fear that enum's can be a pain to update and would result in a new version of the standard but maybe I am just overthinking this, so I won't object to the idea. Since there already is a logger oem enum I don't think there is anything wrong with adding another enum. What do you think @stephenholleran ?

**Comment by abohara** [comment]
I support @heikowestermann . For the current version of things / maintainability concern I would support it being a simple text field. Fewer tables I think help with adoption and digestibility, especially for a possible new adopter.

**Comment by stephenholleran** [comment]
Decided to close.
